[general]
library_name = "libcurl"
module_name = "LibCURL2"
use_julia_native_enum_type = true
use_deterministic_symbol = true
auto_mutability = true
print_enum_as_integer = true

printer_blacklist = [
    "CURL_SUFFIX_CURL_OFF_T",
    "CURL_SUFFIX_CURL_OFF_TU",
    "CURL_ZERO_TERMINATED",
    "CURL_EXTERN",
    "CURL_SOCKET_BAD"
]

prologue_file_path = "./prologue.jl"
# epilogue_file_path = "./epilogue.jl"

[codegen]
use_ccall_macro = true
wrap_variadic_function = true

[codegen.macro]
macro_mode = "basic"